name: ci 
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - run: pip install mkdocs-material==9.7.7 mkdocs-glightbox mkdocs-pygments
      - run: mkdocs gh-deploy --force
